name: humble-devel

on:
  pull_request:
    branches:
      - humble-devel
  push:
    branches:
      - humble-devel
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: humble
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.5
        with:
          package-name: mocap4r2_control mocap4r2_control_msgs rqt_mocap4r2_control mocap4r2_marker_publisher mocap4r2_marker_viz mocap4r2_marker_viz_srvs
          target-ros2-distro: humble
          vcs-repo-file-url: https://raw.githubusercontent.com/MOCAP4ROS2-Project/mocap/rolling/dependency_repos.repos
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
